[[main]]
  name = "Book"
  url = "/book/"
  weight = 10

[[main]]
  name = "About"
  url = "/about/"
  weight = 20

[[main]]
  name = "Gallery"
  url = "/gallery/"
  weight = 30

[[main]]
  name = "Contact"
  url = "/contact/"
  weight = 40
