[[main]]
  identifier = "home"
  name = "Hjem"
  url = "/"
  weight = 10
  [main.params]
    icon = "home"

[[main]]
  identifier = "videos"
  name = "Videoer"
  url = "/videos/"
  weight = 20
  [main.params]
    icon = "play"

[[main]]
  identifier = "books"
  name = "Bøger"
  url = "/books/"
  weight = 30
  [main.params]
    icon = "book"
    comingSoon = true

[[main]]
  identifier = "gallery"
  name = "Galleri"
  url = "/gallery/"
  weight = 40
  [main.params]
    icon = "image"
    comingSoon = true

[[main]]
  identifier = "contact"
  name = "Kontakt"
  url = "/contact/"
  weight = 50
  [main.params]
    icon = "mail"
