[[main]]
  identifier = "home"
  name = "ꯃꯇꯦꯡ ꯄꯥꯟꯕ"
  url = "/"
  weight = 10
  [main.params]
    icon = "home"

[[main]]
  identifier = "videos"
  name = "ꯚꯤꯗꯤꯑꯣ"
  url = "/videos/"
  weight = 20
  [main.params]
    icon = "play"

[[main]]
  identifier = "books"
  name = "ꯄꯨꯛꯁꯤꯟ"
  url = "/books/"
  weight = 30
  [main.params]
    icon = "book"

[[main]]
  identifier = "gallery"
  name = "ꯒꯦꯂꯔꯤ"
  url = "/gallery/"
  weight = 40
  [main.params]
    icon = "image"
    comingSoon = true

[[main]]
  identifier = "contact"
  name = "ꯁꯥꯛꯍꯧꯕ"
  url = "/contact/"
  weight = 50
  [main.params]
    icon = "mail"
