[[main]]
  identifier = "home"
  name = "Startseite"
  url = "/"
  weight = 10
  [main.params]
    icon = "home"

[[main]]
  identifier = "videos"
  name = "Videos"
  url = "/videos/"
  weight = 20
  [main.params]
    icon = "play"

[[main]]
  identifier = "books"
  name = "Bücher"
  url = "/books/"
  weight = 30
  [main.params]
    icon = "book"

[[main]]
  identifier = "gallery"
  name = "Galerie"
  url = "/gallery/"
  weight = 40
  [main.params]
    icon = "image"

[[main]]
  identifier = "contact"
  name = "Kontakt"
  url = "/contact/"
  weight = 50
  [main.params]
    icon = "mail"
