[[main]]
  name = "Livre"
  url = "/book/"
  weight = 10

[[main]]
  name = "À propos"
  url = "/about/"
  weight = 20

[[main]]
  name = "Galerie"
  url = "/gallery/"
  weight = 30

[[main]]
  name = "Contact"
  url = "/contact/"
  weight = 40
